baseurl = "http://daebum.com"
title = "BumNote"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "BUM"

[params]
    author = "DAEBUM LEE"
    info = "Software engineer and Pre-Papa"
    description = "DAEBUM's personal webpage"
    keywords = "blog,developer,personal,papa"
    avatarurl = "images/daebum-lee-pic.jpg"

    favicon_32 = "images/daevicon.ico"
    favicon_16 = "images/daevicon.ico"

    footercontent = "lifelog"

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 2
    url = "https://github.com/BoomLEE"
[[params.social]]
    name = "Facebook"
    icon = "fab fa-facebook fa-2x"
    weight = 3
    url = "#"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 4
    url = "#"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 1
    url = "#"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/blog/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
